Repository material-components/material-components-android, pull requests merged in 2021-12, with the labels that each got.

#2406 [Material Toolbar] Change logo scaleType and set logo adjustViewBounds
  docs/components/TopAppBar.md
  lib/java/com/google/android/material/appbar/MaterialToolbar.java
  lib/java/com/google/android/material/appbar/res-public/values/public.xml
  lib/java/com/google/android/material/appbar/res/values/attrs.xml
  lib/java/com/google/android/material/internal/ToolbarUtils.java
Labels: cla: yes, Review in Progress

#2237 [BottomSheetDialogFragment] Added constructor that takes a layout ID
  build.gradle
  lib/java/com/google/android/material/bottomsheet/BottomSheetDialogFragment.java
Labels: cla: yes, Waiting For Merge

#2487 Revert "[BottomSheetDialogFragment] Added constructor that takes a layout ID"
  build.gradle
  lib/java/com/google/android/material/bottomsheet/BottomSheetDialogFragment.java
Labels: cla: yes

#2488 Revert "[Material Toolbar] Change logo scaleType and set logo adjustViewBounds"
  docs/components/TopAppBar.md
  lib/java/com/google/android/material/appbar/MaterialToolbar.java
  lib/java/com/google/android/material/appbar/res-public/values/public.xml
  lib/java/com/google/android/material/appbar/res/values/attrs.xml
  lib/java/com/google/android/material/internal/ToolbarUtils.java
Labels: cla: yes
